# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
# IP: The module: 'clk_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/summer_school/SEA-master/Examples/FPGA/4.Module-Interface/Gyro-Interface/Gyro_Demo_Verilog/Gyro_Demo/Gyro_Demo.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
