# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'Lab_0_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0.xci
# IP: The module: 'Lab_0_rst_clk_wiz_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/summer_school/dazuoye/Lab0/Lab0.srcs/sources_1/bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_0_rst_clk_wiz_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
