# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/Lab_0/Lab_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0 || ORIG_REF_NAME==Lab_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_microblaze_0_0/Lab_0_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_microblaze_0_0 || ORIG_REF_NAME==Lab_0_microblaze_0_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_axi_iic_0_0/Lab_0_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_axi_iic_0_0 || ORIG_REF_NAME==Lab_0_axi_iic_0_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_axi_uartlite_0_0/Lab_0_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_axi_uartlite_0_0 || ORIG_REF_NAME==Lab_0_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_clk_wiz_0_0/Lab_0_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_clk_wiz_0_0 || ORIG_REF_NAME==Lab_0_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_dlmb_v10_0/Lab_0_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_dlmb_v10_0 || ORIG_REF_NAME==Lab_0_dlmb_v10_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_ilmb_v10_0/Lab_0_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_ilmb_v10_0 || ORIG_REF_NAME==Lab_0_ilmb_v10_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_dlmb_bram_if_cntlr_0/Lab_0_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab_0_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_ilmb_bram_if_cntlr_0/Lab_0_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Lab_0_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_lmb_bram_0/Lab_0_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_lmb_bram_0 || ORIG_REF_NAME==Lab_0_lmb_bram_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_mdm_1_0/Lab_0_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_mdm_1_0 || ORIG_REF_NAME==Lab_0_mdm_1_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_rst_clk_wiz_0_100M_0/Lab_0_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==Lab_0_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_xbar_0/Lab_0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_xbar_0 || ORIG_REF_NAME==Lab_0_xbar_0} -quiet] -quiet

# IP: bd/Lab_0/ip/Lab_0_microblaze_0_axi_periph_0/Lab_0_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_0_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Lab_0_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/Lab_0/Lab_0_ooc.xdc
